# Generated by Django 5.1.6 on 2025-02-27 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='ward',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('totalbeds', models.CharField(max_length=50)),
                ('availablebeds', models.CharField(max_length=50)),
            ],
        ),
    ]
